flags:
  red:
    world: world
    x: 0
    y: 0
    z: 0
  blue:
    world: world
    x: 0
    y: 0
    z: 0
spawns:
  red:
    loc1:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
  blue:
    loc1:
      world: world
      x: 0.0
      y: 64.5
      z: 0.0
